resolver: lts-13.0

packages:
  - summoner-cli/
  - summoner-tui/

extra-deps:
  - brick-0.41.4
  - config-ini-0.2.4.0
  - data-clist-0.1.2.1
  - hedgehog-0.6.1
  - pretty-show-1.8.2
  - text-zipper-0.10.1
  - word-wrap-0.4.1

# This is because `data-clist` has tough bounds for `QuickCheck`.
allow-newer: true
