resolver: lts-13.1

packages:
  - summoner-cli/
  - summoner-tui/

extra-deps:
  - brick-0.41.4
  - config-ini-0.2.4.0  # needed for brick
  - data-clist-0.1.2.2  # needed for brick
  - text-zipper-0.10.1  # needed for brick
  - word-wrap-0.4.1     # needed for brick
