resolver: lts-15.5

packages:
  - summoner-cli/
  - summoner-tui/

extra-deps:
  - colourista-0.1.0.0
  - generic-data-0.8.0.0
  - hspec-hedgehog-0.0.1.1
  - relude-0.7.0.0
  - tomland-1.3.0.0
  - validation-selective-0.1.0.0
  - microaeson-0.1.0.0
