resolver: lts-17.9

packages:
  - summoner-cli/
  - summoner-tui/

extra-deps:
  - colourista-0.1.0.1
  - generic-data-0.8.0.0
  - relude-1.0.0.1
  - tomland-1.3.3.0
  - optparse-applicative-0.16.0.0
  - git: git@github.com:kowainik/microaeson.git
    commit: 0630d4d8c6d912180b35795dc462f8ea75affa99
