name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        cabal: ["2.4"]
        ghc:
          - "8.4.4"
          - "8.6.5"
          - "8.8.3"
          - "8.10.1"

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Build
      run: |
        cabal v2-update
        cabal v2-build all --enable-tests --enable-benchmarks

    - name: Unit and property tests
      run: |
        cabal v2-test all --enable-tests

    - if: matrix.ghc == '8.8.3'
      name: Build 'cabal-minimal'
      run: |
        cd "summoner-cli/examples/cabal-minimal/"
        echo "packages: ." > cabal.project
        cabal v2-build all

    - name: Build 'cabal-full'
      run: |
        cd "summoner-cli/examples/cabal-full/"
        echo "packages: ." > cabal.project
        cabal v2-build all

    - name: Build 'stack-full'
      run: |
        cd "summoner-cli/examples/stack-full/"
        echo "packages: ." > cabal.project
        cabal v2-build all

    - name: Build 'full-batteries'
      run: |
        cd "summoner-cli/examples/full-batteries/"
        echo "packages: ." > cabal.project
        cabal v2-build all
